### ISSUE TITLE
Allow Fractional Scaling in Budgie Display Settings

### ISSUE THREAD

**Issue by joeldeteves** [Ultramarine-Linux/ultramarine#12]
I currently have 2 x 4k monitors, which work fine at 2k resolution but are too small to read at 4k resolution.

It used to be that using 4k monitors on Linux was not feasible, however it's since come along way - for example, in Ubuntu Budgie, there is an option in the Budgie Control Panel to enable fractional scaling under the Display Settings.

I would like to see this option made available in Ultramarine Linux as well.

I tried enabling Fractional Scaling as follows:
`settings set org.gnome.mutter experimental-features “['scale-monitor-framebuffer']”` however the additional settings do not appear in the Budgie Display Settings as they do in the Ubuntu spin.

I am unsure whether this is a custom thing done by the Ubuntu Budgie team, but it would be nice to have on a Fedora-based distribution (and Ultramarine is the best Budgie-based spin I've found thus far).

**Comment by trobonox** [comment]
I have looked into this issue, and it seems like in the implementation of this feature in the Budgie Control Panel source code, it says that Mutter fractional scaling only applies to Manjaro and Ubuntu. (Source: https://github.com/BuddiesOfBudgie/budgie-control-center/blob/f8a8b0b2e9dc3b76791e5065fc4fdfa821aae3f6/panels/display/cc-display-config.c#L441)
This is why I'm afraid that unless we patch Mutter ourselves (and maybe patch the Budgie Control Panel), fractional scaling will not work.

Since Budgie is running on X11, your fractional scaling command from above will not work (that only works on Wayland), but you can try using some hacks like this shell script called [x-11-fractional-display-scaling](https://github.com/burntcustard/x11-fractional-display-scaling), or try installing a similar patch like the one Ubuntu is using for X11 fractional scaling under the hood, which has been ported by someone: https://copr.fedorainfracloud.org/coprs/lukajan/xorg-fractional-scaling/ (but this is a little outdated so you might encounter some issues with an outdated patched mutter version)

This is an issue I've been struggling with myself, and sadly on GTK based DEs running X11 there is no optimal solution that comes preinstalled. Maybe this will change for the better in the future with new versions of Mutter and Budgie releasing.

I hope this was a little helpful, don't hesitate to ask more questions if you require further assistance.

**Comment by joeldeteves** [comment]
Thank you @trobonox this explanation is very helpful.

It looks like the most compatible option for now is to simply reduce the resolution of my displays to 2k, which still looks great on Ultramarine + Budgie btw.

I do think we will see some improvements soon as the Budgie team are working on a near-complete rewrite for Budgie 11 - in addition, they're working with the Fedora team on bringing a Budgie spin to Fedora so this will likely have the added benefit of making Budgie more compatible with modern setups.

That aside I also like the out-of-the-box setup on Ultramarine - the defaults are sane and the added repositories are nice so kudos for that.

Hope to see both projects succeed in the future 🥂
