### ISSUE TITLE
[FEATURE REQUEST] Deliver preinstalled apps via Flathub; provide them in a way that does not require rpm-ostree overrides to remove

### ISSUE THREAD

**Issue by bleper** [Ultramarine-Linux/ultramarine#28]
Without this, to update applications regardless of the system, choose alternatives or remove unnecessary ones, we have to rebase the system, removing these packages from it, and install them through Flathub.

A simple solution would be to leave as system applications only those that are not provided as Flatpaks, and install the rest as non-system applications via Flathub during system installation or on first launch, providing users with a list of applications to choose from.

Another solution would be to develop a system application manager in graphical form, if for some reason someone needs this.

This applies to at least the atomic version of the system.

**Comment by madonuko** [comment]
We are already doing this for the Pantheon edition: packages are installed as flatpaks on x86_64 while they are installed as RPMs from Terra on aarch64 (since Elementary does not provide aarch64 flatpaks)

Switching the RPMs to Flatpaks is basically equivalent to `dnf5 rm pkgname -y && flatpak install org.idk.pkgname`. The problem is, it is impossible to be certain about which flatpak name corresponds to the RPM package, meaning user intervention is usually required.

The way around this is, yeah, either making a new software centre, or asking GNOME if they care enough to add such a feature into their version of software centre. I doubt if they'll do that though since it's pretty niche…

I don't really understand the use case behind this but I noticed you talked about not having the ability to do this on immutable (because… it's immutable). I reckon we can allow some way around this during setup, I'll ask someone more familiar with immutables.

**Comment by lleyton** [comment]
Heya, thanks for opening this issue, I agree with what was said here. For the atomic variants, we will be moving the pre-installed applications from in-tree RPMs to Flatpak. The atomic variants are in beta, so it's not currently reflective of what it will look like in the final release.

As for Ultramarine as a whole (including mutable variants), our plans for pre-installed desktop applications is to move all of them to Flatpaks, when the UX is equivalent or better than the RPM variant. This is expected to fully roll out in Ultramarine 40, but we're currently running an experiment with this model for 39's Pantheon variant, as @madonuko mentioned. This falls in line with our belief that Flatpak is the future of application distribution and our goal to realize/push that future. As far I as remember, this isn't even something Fedora is doing/planning in their mutable variants.

I think your idea of allowing the user to select the apps (as Flatpaks) they want, on install, is pretty neat, and I'll be talking to the rest of the team to get it in UM 40 :). As for migration of existing RPMs to Flatpak, I think it would be able to possible to utilize the appstream metadata to match the applications, as software stores such as GNOME Software currently do. That's something that I would have to look into more though.

Anyways, please let me know if you have any feedback or other ideas on this, because putting Flatpak in the hands of more users is something that we're really interested in :)

(P.S. I'm in the [Ultramarine Discord](https://discord.gg/bUuQasHdrF) as `lleyton.` if you'd rather discuss further there.)
