### ISSUE TITLE
[PACKAGE REQUEST] Update Budgie to version 10.6.1

### ISSUE THREAD

**Issue by glexposito** [Ultramarine-Linux/ultramarine#6]
neofetch command reports Budgie v10.5.3
![image](https://user-images.githubusercontent.com/1209324/174514619-532b71d4-7be8-48cf-a023-0bb7ed8ae1e6.png)

**Comment by windowsboy111** [comment]
[The Budgie version has already been updated to 10.6.1 since 7 March.](https://github.com/Ultramarine-Linux/pkg-budgie-desktop/blob/lapis/budgie-desktop.spec#L10) Please update your own budgie version via `dnf`.
![image](https://user-images.githubusercontent.com/48051237/174804217-637980da-dd26-4e40-ac05-4ef4e1b93500.png)
